### ISSUE TITLE
Issue with C library

### ISSUE THREAD

**Issue by almos** [JumpMind/symmetric-ds#19]
Hi,

I am trying to run C library (https://github.com/JumpMind/symmetric-ds/tree/3.7/symmetric-client-clib)
I have configured it according to the instructions. For some reason custom tables aren't created.

Symmetric tables get created and even populated with data from server, i.e.:

`sqlite> SELECT name FROM sqlite_master WHERE type='table';
sym_channel
sym_data
sqlite_sequence
sym_data_event
sym_incoming_batch
sym_node
sym_node_security
sym_node_group
sym_node_group_link
sym_node_host
sym_node_identity
sym_outgoing_batch
sym_parameter
sym_router
sym_sequence
sym_trigger
sym_trigger_hist
sym_trigger_router`

`sqlite> select * from sym_router;
client_2_server||||client|server|default||1|1|1|1|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
server_2_client||||server|client|default||1|1|1|1|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189`

`sqlite> select * from sym_trigger
   ...> ;
Comment|||Comment|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
CommentImage|||CommentImage|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
Object|||Object|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
object_comment|||object_comment|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
SyncAudit|||SyncAudit|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
TaskAudit|||TaskAudit|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
task_comment|||task_comment|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
TestPlan|||TestPlan|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
Testtask|||Testtask|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
UserDetails|||UserDetails|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189
UserLogin|||UserLogin|sync_data|reload|1|1|1|0|||||||||||||||0|0|1|0|2016-03-09 16:56:37.367189||2016-03-09 16:56:37.367189`

Full log is here: http://pastebin.com/1yYqnH2d.

What may be the problem?

Regards,
Alex

**Comment by erilong** [comment]
The C client doesn't support "C" (create table) event types yet.  There's some work to be done there, like parsing the Torque XML and translating it into compatible DDL for SQLite.  To work around the current limitation, you could send "S" (SQL) event types that contain the create DDL statements you want to run on SQLite.  An easy way to do that is put all your SQL statements into the initial.load.before.sql parameter (in sym_parameter table), separating multiple statements by a semi-colon, and they will be sent at the beginning of the initial load automatically.  I hope that helps.

**Comment by almos** [comment]
Thank you for the reply. So initial schema creation is not supported.

But what about schema updates?
If table is added a column, would existing implementation manage this column creation on the client SQLite side?

**Comment by erilong** [comment]
The schema updates are also based on the "C" events (symadmin send-schema), so that is not supported yet either.  You could sent "S" events (symadmin send-sql) to send the alter statements to add columns.
