### ISSUE TITLE
[Question] Is it possible to store sym tables on a separate database?

### ISSUE THREAD

**Issue by Gidipp** [JumpMind/symmetric-ds#22]
I have tried to use SymmetricDS to replicate one MySQL database to a destination MySQL database. 

When SymmetricDS starts it creates many tables inside the database I want to replicate from. 

Is it possible to configure the software to use a separate database for this tables?

Thanks

**Comment by chenson42** [comment]
You can use a separate catalog/database on MySQL for SymmetricDS.  The same database user you configure needs access to the catalog/database you want to sync and you set the source_catalog_name in sym_trigger to point to the catalog/database your table is in.
