### ISSUE TITLE
Android node for SQLite support

### ISSUE THREAD

**Issue by ahmedelfa** [JumpMind/symmetric-ds#6]
I've followed this tutorial 
http://www.jumpmind.com/blog/synchronizing-android-applications-part1

it doesn't work I get these errror messages : 
1-03 10:57:05.155 3738-3738/? E/AndroidRuntime: FATAL EXCEPTION: main
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime: Process: najlae.com.contentprovidertest, PID: 3738
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime: java.lang.NoClassDefFoundError: com.mysql.jdbc.StringUtils
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.db.sqlite.SqliteTriggerTemplate.<init>(SqliteTriggerTemplate.java:39)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.db.sqlite.SqliteSymmetricDialect.<init>(SqliteSymmetricDialect.java:51)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.android.AndroidSymmetricEngine.createSymmetricDialect(AndroidSymmetricEngine.java:126)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.AbstractSymmetricEngine.init(AbstractSymmetricEngine.java:296)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.android.AndroidSymmetricEngine.<init>(AndroidSymmetricEngine.java:79)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at org.jumpmind.symmetric.android.SymmetricService.onStartCommand(SymmetricService.java:87)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2702)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.app.ActivityThread.access$2100(ActivityThread.java:135)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5021)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
11-03 10:57:05.155 3738-3738/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

I didn't find sufficient support on the blog. Please help. Thanks

**Comment by chenson42** [comment]
This has been address in the latest version.  A wrong import got checked in.
